### PR TITLE
Change `Session.info` type annotation from Mapping to MutableMapping

### LINKED ISSUE #143: Session.info should be mutable
**Describe the bug**
Editing the `Session.info` dict yields a typing error

**Expected behavior**
Editing the `Session.info` dict should work without errors

**To Reproduce**

```py
from sqlalchemy.orm import Session

session = Session()
session.info["foo"] = "bar"

```

**Error**

```
foo.py:4: error: Unsupported target for indexed assignment ("Mapping[Any, Any]")
Found 1 error in 1 file (checked 1 source file)

```

**Versions.**
 - OS: Debian 10
 - Python: 3.9.6
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a7

**Additional context**
`Session.info` is currently typed as `Mapping[Any, Any]`, thus read-only. I think it should be changed to `MutableMapping[Any, Any]`

**Have a nice day!**

### PR DESCRIPTION
**Pull request by Parnassius**
Fixes #143

### Description
Change `Session.info` type annotation from Mapping to MutableMapping

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [X] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks, this looks fine

It seems that we use mapping everywhere for the `info` prop, like in Table.
It may make sense to change them there also. If you could update them also it would be great!

**Comment by Parnassius** [comment]
Done.
In a few instances (like [Conntection in engine/base.pyi](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/0503ece40148d78432faab1771882169f3b136f1/sqlalchemy-stubs/engine/base.pyi#L68) and [SchemaItem in sql/schema.pyi](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/0503ece40148d78432faab1771882169f3b136f1/sqlalchemy-stubs/sql/schema.pyi#L62)) the `info` property is annotated as `Dict[Any, Any]`, should I change them to `MutableMapping` as well?

**Comment by CaselIT** [comment]
Thanks!

> In a few instances (like Conntection in engine/base.pyi and SchemaItem in sql/schema.pyi) the info property is annotated as Dict[Any, Any], should I change them to MutableMapping as well?

I think it would make sense to uniform them

**Review by CaselIT — APPROVED** [review]
Thanks!

**Comment by CaselIT** [comment]
will release in a bit

**Pull request merged**
