### PR TITLE
Improve typing for the 'get' method in session

### PR DESCRIPTION
**Pull request by heckad**

### CODE REVIEW

**Review by CaselIT — APPROVED** [review]
Ok for me cc @MaicoTimmerman

**Comment by MaicoTimmerman** [comment]
This change looks good to me, however it seems that the https://github.com/sqlalchemy/sqlalchemy/blob/master/test/ext/mypy/files/other_mapper_props.py test-case is failing.

@CaselIT should we update that SQLAlchemy test before merging this?

**Comment by CaselIT** [comment]
I think it would make sense.

**Comment by heckad** [comment]
https://github.com/sqlalchemy/sqlalchemy/pull/6789

**Comment by CaselIT** [comment]
@heckad now that the pr in sqlalchemy is merged we will wait for a release so that also the `3.9-sqla_release` test passes

thanks for the effort

**Comment by CaselIT** [comment]
Now it should work also with the published version of sqlalchemy,

I think we should wait for https://github.com/sqlalchemy/sqlalchemy2-stubs/pull/149 to be merged, and also update all other cases where `.get` is defined

**Review by CaselIT — APPROVED** [review]
thanks

**Pull request merged**
